# Generated by Django 3.0 on 2019-12-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
