# Generated by Django 3.0 on 2020-01-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
    ]
